#!/usr/bin/env php
<?php

require_once dirname(__DIR__).'/vendor/symfony/dotenv/Dotenv.php';

use Symfony\Component\Dotenv\Dotenv;

if (!in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    echo 'Warning: The console should be invoked via the CLI version of PHP, not the '.PHP_SAPI.' SAPI'.PHP_EOL;
}

umask(0000);

if (!is_writable('/etc/nginx/sites-enabled')) {
    echo "Directory '/etc/nginx/sites-enabled' is not writable.\n\nPlease run this script under privileged user.\n\n";
    exit(1);
}

if (!isset($argv[1])) {
    echo "You need to set domain name\n\n";
    exit(1);
}

$domain = $argv[1];

if (file_exists('/etc/nginx/sites-enabled/' . $domain . '.conf')) {
    echo "Domain $domain is exists.\n";
    exit(1);
}

(new Dotenv())->bootEnv(dirname(__DIR__).'/.env');

$dockerConfig = dirname(__DIR__)."/.env.docker.{$_SERVER['APP_ENV']}.local";

if (!file_exists($dockerConfig)) {
    echo "File .env.docker.{$_SERVER['APP_ENV']}.local is NOT exists.\n";
    exit(1);
}

(new Dotenv())->load($dockerConfig);

$conf = file_get_contents(dirname(__DIR__).'/install/configs/nginx.conf');

$conf = str_replace('${DOMAIN}', $domain, $conf);
$conf = str_replace('${WORKING_DIR}', $_SERVER['WORKING_DIR'], $conf);
$conf = str_replace('${PHP_FPM_PROD_PORT}', $_SERVER['PHP_FPM_PROD_PORT'], $conf);

file_put_contents('/etc/nginx/sites-enabled/'.$domain.'.conf', $conf);

system('/etc/init.d/nginx reload');
